apiVersion: apps/v1
kind: Deployment
metadata:
	name: suri-deploy
spec:
	replicas: 2
	selector:
		matchLabels:
			env: prod
	template:
		metadata:
			labels:
				env: prod
		spec:
			containers:
				- name: suri-pod
					image: surendra548/test-java-proj:7
			
